# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-27 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_analytics', models.CharField(blank=True, help_text=b'UA-XXXXX-X', max_length=15, verbose_name='Google Analytics')),
                ('promotions', models.URLField(blank=True, max_length=255, verbose_name='Promotions')),
                ('reserve', models.URLField(blank=True, max_length=255, verbose_name='Reserve')),
                ('occ', models.URLField(blank=True, max_length=255, verbose_name='Occ')),
                ('discover', models.TextField(blank=True, help_text='embed code', verbose_name='Discover')),
            ],
            options={
                'verbose_name': 'Configuration',
            },
        ),
    ]
