# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-18 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0002_initial_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=255, verbose_name='facebook url'),
        ),
        migrations.AddField(
            model_name='home',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=255, verbose_name='intagram url'),
        ),
        migrations.AddField(
            model_name='home',
            name='twitter_url',
            field=models.URLField(blank=True, max_length=255, verbose_name='twitter url'),
        ),
    ]
