# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-18 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0003_auto_20161118_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='max_temp',
            field=models.CharField(blank=True, max_length=255, verbose_name='max temperature'),
        ),
        migrations.AddField(
            model_name='home',
            name='min_temp',
            field=models.CharField(blank=True, max_length=255, verbose_name='min temperature'),
        ),
        migrations.AddField(
            model_name='home',
            name='weather_icon',
            field=models.CharField(blank=True, max_length=10, verbose_name='weather icon'),
        ),
    ]
