# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-18 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0004_auto_20161118_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=255, verbose_name='instagram url'),
        ),
    ]
