# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-19 00:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0005_auto_20161118_2326'),
        ('Configuration', '0005_auto_20161118_2151'),
    ]

    operations = [
    ]
