# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-07 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0006_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='error_banner_image',
            field=models.ImageField(default=1, upload_to=b'configuration_images', verbose_name='Error banner Image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='home',
            name='search_banner_image',
            field=models.ImageField(upload_to=b'configuration_images', verbose_name='Search banner Image'),
        ),
    ]
