# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-13 12:23
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0008_home_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=0, verbose_name='privacy policy'),
            preserve_default=False,
        ),
    ]
