# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-13 12:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0009_home_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='description',
            new_name='privacy_policy',
        ),
    ]
