# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-13 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0010_auto_20170213_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='privacy_policy_banner_image',
            field=models.ImageField(default=0, upload_to=b'configuration_images', verbose_name='Privacy policy banner Image'),
            preserve_default=False,
        ),
    ]
