# Generated by Django 2.2.4 on 2019-09-11 13:45

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0014_metafields_translate'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='meta_description_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='home',
            name='meta_keywords_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='home',
            name='privacy_policy_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='privacy policy'),
        ),
        migrations.AddField(
            model_name='home',
            name='search_subtitle_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Search subtitle'),
        ),
        migrations.AddField(
            model_name='home',
            name='search_title_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Search title'),
        ),
        migrations.AddField(
            model_name='home',
            name='transparency_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Transparency'),
        ),
        migrations.AlterField(
            model_name='home',
            name='error_banner_image',
            field=models.ImageField(blank=True, upload_to='configuration_images', verbose_name='Error banner Image'),
        ),
        migrations.AlterField(
            model_name='home',
            name='google_analytics',
            field=models.CharField(blank=True, help_text='UA-XXXXX-X', max_length=15, verbose_name='Google Analytics'),
        ),
        migrations.AlterField(
            model_name='home',
            name='meta_description_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='home',
            name='meta_description_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='home',
            name='meta_keywords_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='home',
            name='meta_keywords_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='home',
            name='privacy_policy_banner_image',
            field=models.ImageField(blank=True, upload_to='configuration_images', verbose_name='Privacy policy banner Image'),
        ),
        migrations.AlterField(
            model_name='home',
            name='privacy_policy_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='privacy policy'),
        ),
        migrations.AlterField(
            model_name='home',
            name='privacy_policy_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='privacy policy'),
        ),
        migrations.AlterField(
            model_name='home',
            name='search_banner_image',
            field=models.ImageField(blank=True, upload_to='configuration_images', verbose_name='Search banner Image'),
        ),
        migrations.AlterField(
            model_name='home',
            name='search_subtitle_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Search subtitle'),
        ),
        migrations.AlterField(
            model_name='home',
            name='search_subtitle_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Search subtitle'),
        ),
        migrations.AlterField(
            model_name='home',
            name='search_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Search title'),
        ),
        migrations.AlterField(
            model_name='home',
            name='search_title_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Search title'),
        ),
        migrations.AlterField(
            model_name='home',
            name='transparency_banner_image',
            field=models.ImageField(blank=True, upload_to='transparency_images', verbose_name='Transparency banner Image'),
        ),
        migrations.AlterField(
            model_name='home',
            name='transparency_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Transparency'),
        ),
        migrations.AlterField(
            model_name='home',
            name='transparency_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Transparency'),
        ),
    ]
