# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-30 04:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('title_fr', models.CharField(max_length=255, verbose_name='title')),
                ('title_en', models.CharField(max_length=255, verbose_name='title')),
                ('subtitle', models.CharField(max_length=255, verbose_name='sub title')),
                ('subtitle_en', models.CharField(max_length=255, verbose_name='sub title')),
                ('subtitle_fr', models.CharField(max_length=255, verbose_name='sub title')),
                ('description', models.TextField(verbose_name='description')),
                ('description_fr', models.TextField(verbose_name='description')),
                ('description_en', models.TextField(verbose_name='description')),
                ('image', models.ImageField(upload_to=b'cards', verbose_name='image')),
                ('address', models.TextField(verbose_name='Address')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Contact Email')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Phone')),
                ('link', models.URLField(blank=True, max_length=255, verbose_name='Link')),
                ('button_text', models.CharField(blank=True, max_length=255, verbose_name='button text')),
                ('button_text_fr', models.CharField(blank=True, max_length=255, verbose_name='button text')),
                ('button_text_en', models.CharField(blank=True, max_length=255, verbose_name='button text')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('title_en', models.CharField(max_length=255, verbose_name='title')),
                ('title_fr', models.CharField(max_length=255, verbose_name='title')),
                ('image', models.ImageField(upload_to=b'wh_cat_image', verbose_name='image')),
                ('banner_image', models.ImageField(upload_to=b'wh_cat_banner_image', verbose_name='banner image')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('title_en', models.CharField(max_length=255, verbose_name='title')),
                ('title_fr', models.CharField(max_length=255, verbose_name='title')),
                ('excerpt', models.TextField(verbose_name='excerpt')),
                ('excerpt_fr', models.TextField(verbose_name='excerpt')),
                ('excerpt_en', models.TextField(verbose_name='excerpt')),
                ('banner_image', models.ImageField(upload_to=b'banner_posts', verbose_name='banner image')),
            ],
            options={
                'verbose_name': 'Configuration',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('name_fr', models.CharField(max_length=255, verbose_name='name')),
                ('name_en', models.CharField(max_length=255, verbose_name='name')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'ordering': ('order',),
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='tags',
            field=models.ManyToManyField(related_name='categories', to='WhatsHot.Tag', verbose_name='tag'),
        ),
        migrations.AddField(
            model_name='card',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='WhatsHot.Category', verbose_name='category'),
        ),
    ]
