# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-10 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WhatsHot', '0002_initial_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='outstanding',
            field=models.BooleanField(default=False, verbose_name='Outstanding'),
        ),
    ]
