# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-10 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WhatsHot', '0003_card_outstanding'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='subheading',
            field=models.CharField(default=0, max_length=255, verbose_name='sub heading'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='subheading_en',
            field=models.CharField(default=0, max_length=255, verbose_name='sub heading'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='subheading_fr',
            field=models.CharField(default=0, max_length=255, verbose_name='sub heading'),
            preserve_default=False,
        ),
    ]
