# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-10 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WhatsHot', '0004_auto_20161010_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('title_en', models.CharField(max_length=255, verbose_name='title')),
                ('title_fr', models.CharField(max_length=255, verbose_name='title')),
                ('image', models.ImageField(upload_to=b'sections', verbose_name='image')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('cards', models.ManyToManyField(related_name='sections', to='WhatsHot.Card', verbose_name='card')),
                ('categories', models.ManyToManyField(related_name='sections', to='WhatsHot.Category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
            },
        ),
    ]
