# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-10 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WhatsHot', '0005_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='outstanding',
        ),
        migrations.AddField(
            model_name='section',
            name='outstanding',
            field=models.BooleanField(default=False, verbose_name='Outstanding'),
        ),
    ]
