# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-10 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WhatsHot', '0006_auto_20161010_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='cards',
        ),
        migrations.AddField(
            model_name='card',
            name='sections',
            field=models.ManyToManyField(related_name='cards', to='WhatsHot.Section', verbose_name='section'),
        ),
    ]
