# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-18 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WhatsHot', '0008_auto_20161010_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='tags',
        ),
    ]
