# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-18 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WhatsHot', '0009_remove_category_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='tags',
            field=models.ManyToManyField(related_name='sections', to='WhatsHot.Tag', verbose_name='tag'),
        ),
    ]
