# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-19 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WhatsHot', '0010_section_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=0, max_length=255, verbose_name='slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='slug_en',
            field=models.SlugField(default=0, max_length=255, verbose_name='slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='slug_fr',
            field=models.SlugField(default=0, max_length=255, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
