# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-19 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WhatsHot', '0011_auto_20161019_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='slug',
            field=models.CharField(default=0, max_length=255, verbose_name='slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='slug_en',
            field=models.CharField(default=0, max_length=255, verbose_name='slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='slug_fr',
            field=models.CharField(default=0, max_length=255, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
