# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-19 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WhatsHot', '0013_auto_20161019_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.CharField(default=1, max_length=255, verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='description_fr',
            field=models.CharField(default=1, max_length=255, verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(default=1, max_length=255, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='name_fr',
            field=models.CharField(default=1, max_length=255, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='description_en',
            field=models.CharField(default=1, max_length=255, verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='description_fr',
            field=models.CharField(default=1, max_length=255, verbose_name='description'),
            preserve_default=False,
        ),
    ]
