# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-19 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WhatsHot', '0014_auto_20161019_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
