# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-20 12:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WhatsHot', '0015_auto_20161019_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='category',
        ),
    ]
