# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-18 23:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WhatsHot', '0016_remove_card_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'whatshot_card_photos', verbose_name='image')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='order')),
            ],
            options={
                'ordering': ('order',),
                'verbose_name': 'Card Photo',
                'verbose_name_plural': 'Card Photos',
            },
        ),
        migrations.AddField(
            model_name='card',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=255, verbose_name='Facebook url'),
        ),
        migrations.AddField(
            model_name='card',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=255, verbose_name='Instagram url'),
        ),
        migrations.AddField(
            model_name='card',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='card',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='longitude'),
        ),
        migrations.AddField(
            model_name='card',
            name='phone_2',
            field=models.CharField(blank=True, max_length=15, verbose_name='Phone 2'),
        ),
        migrations.AddField(
            model_name='card',
            name='phone_3',
            field=models.CharField(blank=True, max_length=15, verbose_name='Phone 3'),
        ),
        migrations.AddField(
            model_name='card',
            name='slug',
            field=models.SlugField(default=1, max_length=255, verbose_name='slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='slug_en',
            field=models.SlugField(default=1, max_length=255, verbose_name='slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='slug_fr',
            field=models.SlugField(default=1, max_length=255, verbose_name='slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='twitter_url',
            field=models.URLField(blank=True, max_length=255, verbose_name='Twitter url'),
        ),
        migrations.AddField(
            model_name='card',
            name='web_site',
            field=models.CharField(blank=True, max_length=255, verbose_name='Web Site'),
        ),
        migrations.AlterField(
            model_name='card',
            name='address',
            field=models.TextField(blank=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='cardphoto',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_photos', to='WhatsHot.Card', verbose_name='Card'),
        ),
    ]
