# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-09 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WhatsHot', '0021_card_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='button_360_link',
            field=models.URLField(blank=True, max_length=255, verbose_name='Button 360 Link'),
        ),
        migrations.AddField(
            model_name='card',
            name='button_360_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='button 360 text'),
        ),
        migrations.AddField(
            model_name='card',
            name='button_360_text_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='button 360 text'),
        ),
        migrations.AddField(
            model_name='card',
            name='button_360_text_fr',
            field=models.CharField(blank=True, max_length=255, verbose_name='button 360 text'),
        ),
        migrations.AddField(
            model_name='card',
            name='excerpt',
            field=models.TextField(default=1, help_text='Excerpt to display on search results and short descriptions', verbose_name='excerpt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='excerpt_en',
            field=models.TextField(default=1, help_text='Excerpt to display on search results and short descriptions', verbose_name='excerpt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='excerpt_fr',
            field=models.TextField(default=1, help_text='Excerpt to display on search results and short descriptions', verbose_name='excerpt'),
            preserve_default=False,
        ),
    ]
