# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-14 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WhatsHot', '0024_auto_20161214_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='tags',
            field=models.ManyToManyField(related_name='sections', to='WhatsHot.Tag', verbose_name='filter'),
        ),
    ]
