# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-14 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WhatsHot', '0025_auto_20161214_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='cards', to='WhatsHot.Section', verbose_name='section'),
        ),
    ]
