# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-16 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WhatsHot', '0026_auto_20161214_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('name_fr', models.CharField(max_length=255, verbose_name='name')),
                ('name_en', models.CharField(max_length=255, verbose_name='name')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'Category Filter',
                'verbose_name_plural': 'Category Filters',
            },
        ),
        migrations.CreateModel(
            name='CategoryFilterOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('name_fr', models.CharField(max_length=255, verbose_name='name')),
                ('name_en', models.CharField(max_length=255, verbose_name='name')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('category_filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='WhatsHot.CategoryFilter', verbose_name='category filter')),
            ],
            options={
                'ordering': ('order',),
                'verbose_name': 'Category Filter Option',
                'verbose_name_plural': 'Category Filter Options',
            },
        ),
        migrations.AddField(
            model_name='card',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='cards', to='WhatsHot.Category', verbose_name='categories'),
        ),
        migrations.AddField(
            model_name='category',
            name='has_sections',
            field=models.BooleanField(default=True, verbose_name='has sections'),
        ),
        migrations.AlterField(
            model_name='card',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='cards', to='WhatsHot.Section', verbose_name='sections'),
        ),
        migrations.AddField(
            model_name='card',
            name='category_filters',
            field=models.ManyToManyField(blank=True, related_name='cards', to='WhatsHot.CategoryFilterOption', verbose_name='category filters'),
        ),
        migrations.AddField(
            model_name='category',
            name='filters',
            field=models.ManyToManyField(blank=True, help_text="only if category doesn't have sections", to='WhatsHot.CategoryFilter'),
        ),
    ]
