# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-23 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WhatsHot', '0027_auto_20161216_1116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ('title',), 'verbose_name': 'Card', 'verbose_name_plural': 'Cards'},
        ),
    ]
