# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-22 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WhatsHot', '0027_auto_20161216_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Keyword',
                'verbose_name_plural': 'Keywords',
            },
        ),
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ('title',), 'verbose_name': 'Card', 'verbose_name_plural': 'Cards'},
        ),
        migrations.AddField(
            model_name='card',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='cards', to='WhatsHot.Keyword', verbose_name='keywords'),
        ),
    ]
