# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-22 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WhatsHot', '0028_auto_20161222_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='name_en',
            field=models.CharField(default=0, max_length=255, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keyword',
            name='name_fr',
            field=models.CharField(default=0, max_length=255, verbose_name='name'),
            preserve_default=False,
        ),
    ]
