# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-03 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WhatsHot', '0029_auto_20161222_1621'),
        ('WhatsHot', '0028_auto_20161223_1233'),
    ]

    operations = [
    ]
