# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-10 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WhatsHot', '0031_auto_20170110_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='WhatsHot.Category', verbose_name='category'),
        ),
    ]
