# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-11 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WhatsHot', '0032_auto_20170110_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='tags',
        ),
        migrations.AddField(
            model_name='section',
            name='category_filters',
            field=models.ManyToManyField(blank=True, related_name='sections', to='WhatsHot.CategoryFilterOption', verbose_name='category filters'),
        ),
        migrations.AlterField(
            model_name='category',
            name='filters',
            field=models.ManyToManyField(blank=True, to='WhatsHot.CategoryFilter'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
