# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-14 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WhatsHot', '0033_auto_20170111_1609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ('order',), 'verbose_name': 'Section WH', 'verbose_name_plural': 'Sections WH'},
        ),
        migrations.AlterField(
            model_name='category',
            name='filters',
            field=models.ManyToManyField(blank=True, to='WhatsHot.CategoryFilter', verbose_name='category filter'),
        ),
    ]
