# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-14 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WhatsHot', '0034_auto_20170214_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.CharField(max_length=255, verbose_name='sub title'),
        ),
        migrations.AlterField(
            model_name='section',
            name='description_en',
            field=models.CharField(max_length=255, verbose_name='sub title'),
        ),
        migrations.AlterField(
            model_name='section',
            name='description_fr',
            field=models.CharField(max_length=255, verbose_name='sub title'),
        ),
    ]
