# Generated by Django 2.2.4 on 2019-09-11 13:45

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WhatsHot', '0037_metafields_translate'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='button_360_text_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='button 360 text'),
        ),
        migrations.AddField(
            model_name='card',
            name='button_text_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='button text'),
        ),
        migrations.AddField(
            model_name='card',
            name='description_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='card',
            name='excerpt_es',
            field=models.TextField(help_text='Excerpt to display on search results and short descriptions', null=True, verbose_name='excerpt'),
        ),
        migrations.AddField(
            model_name='card',
            name='meta_description_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='card',
            name='meta_keywords_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='card',
            name='slug_es',
            field=models.SlugField(max_length=255, null=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='card',
            name='subheading_es',
            field=models.CharField(max_length=255, null=True, verbose_name='sub heading'),
        ),
        migrations.AddField(
            model_name='card',
            name='subtitle_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=255, null=True, verbose_name='sub title'),
        ),
        migrations.AddField(
            model_name='card',
            name='title_es',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_es',
            field=models.CharField(max_length=255, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_keywords_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_es',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_es',
            field=models.SlugField(max_length=255, null=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_es',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='categoryfilter',
            name='name_es',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='categoryfilteroption',
            name='name_es',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='name_es',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='section',
            name='description_es',
            field=models.CharField(max_length=255, null=True, verbose_name='sub title'),
        ),
        migrations.AddField(
            model_name='section',
            name='meta_description_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='section',
            name='meta_keywords_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='section',
            name='slug_es',
            field=models.CharField(max_length=255, null=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='section',
            name='title_es',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='card',
            name='button_360_text_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='button 360 text'),
        ),
        migrations.AlterField(
            model_name='card',
            name='button_360_text_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='button 360 text'),
        ),
        migrations.AlterField(
            model_name='card',
            name='button_text_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='button text'),
        ),
        migrations.AlterField(
            model_name='card',
            name='button_text_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='button text'),
        ),
        migrations.AlterField(
            model_name='card',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='card',
            name='description_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='card',
            name='excerpt_en',
            field=models.TextField(help_text='Excerpt to display on search results and short descriptions', null=True, verbose_name='excerpt'),
        ),
        migrations.AlterField(
            model_name='card',
            name='excerpt_fr',
            field=models.TextField(help_text='Excerpt to display on search results and short descriptions', null=True, verbose_name='excerpt'),
        ),
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(upload_to='cards', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='card',
            name='meta_description_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='card',
            name='meta_description_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='card',
            name='meta_keywords_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='card',
            name='meta_keywords_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='card',
            name='slug_en',
            field=models.SlugField(max_length=255, null=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='card',
            name='slug_fr',
            field=models.SlugField(max_length=255, null=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='card',
            name='subheading_en',
            field=models.CharField(max_length=255, null=True, verbose_name='sub heading'),
        ),
        migrations.AlterField(
            model_name='card',
            name='subheading_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='sub heading'),
        ),
        migrations.AlterField(
            model_name='card',
            name='subtitle_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=255, null=True, verbose_name='sub title'),
        ),
        migrations.AlterField(
            model_name='card',
            name='subtitle_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=255, null=True, verbose_name='sub title'),
        ),
        migrations.AlterField(
            model_name='card',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='card',
            name='title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='cardphoto',
            name='image',
            field=models.ImageField(upload_to='whatshot_card_photos', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='banner_image',
            field=models.ImageField(upload_to='cat_banner_image', verbose_name='banner image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description_en',
            field=models.CharField(max_length=255, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_description_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_description_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_keywords_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_keywords_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug_en',
            field=models.SlugField(max_length=255, null=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug_fr',
            field=models.SlugField(max_length=255, null=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='categoryfilter',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='categoryfilter',
            name='name_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='categoryfilteroption',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='categoryfilteroption',
            name='name_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='name_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='section',
            name='banner_image',
            field=models.ImageField(upload_to='sec_banner_image', verbose_name='banner image'),
        ),
        migrations.AlterField(
            model_name='section',
            name='description_en',
            field=models.CharField(max_length=255, null=True, verbose_name='sub title'),
        ),
        migrations.AlterField(
            model_name='section',
            name='description_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='sub title'),
        ),
        migrations.AlterField(
            model_name='section',
            name='image',
            field=models.ImageField(upload_to='sections', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='section',
            name='meta_description_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='section',
            name='meta_description_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='section',
            name='meta_keywords_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='section',
            name='meta_keywords_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='section',
            name='slug_en',
            field=models.CharField(max_length=255, null=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='section',
            name='slug_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
    ]
