# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-03 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Regions', '0002_initial_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='link',
            field=models.CharField(blank=True, max_length=255, verbose_name='Link'),
        ),
    ]
