# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-16 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Regions', '0004_auto_20161104_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='button_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='button text'),
        ),
        migrations.AddField(
            model_name='section',
            name='button_text_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='button text'),
        ),
        migrations.AddField(
            model_name='section',
            name='button_text_fr',
            field=models.CharField(blank=True, max_length=255, verbose_name='button text'),
        ),
    ]
