# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-18 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Regions', '0005_auto_20161116_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='slug',
            field=models.SlugField(default=1, max_length=255, verbose_name='slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='slug_en',
            field=models.SlugField(default=1, max_length=255, verbose_name='slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='slug_fr',
            field=models.SlugField(default=1, max_length=255, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
