# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-18 21:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Regions', '0006_auto_20161118_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'region_section_photos', verbose_name='image')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='order')),
            ],
            options={
                'ordering': ('order',),
                'verbose_name': 'Section Photo',
                'verbose_name_plural': 'Section Photos',
            },
        ),
        migrations.AddField(
            model_name='section',
            name='address',
            field=models.TextField(blank=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='section',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Contact Email'),
        ),
        migrations.AddField(
            model_name='section',
            name='content',
            field=models.TextField(blank=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='section',
            name='content_en',
            field=models.TextField(blank=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='section',
            name='content_fr',
            field=models.TextField(blank=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='section',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 11, 18, 21, 47, 9, 780515), verbose_name='Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=255, verbose_name='Facebook url'),
        ),
        migrations.AddField(
            model_name='section',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=255, verbose_name='Instagram url'),
        ),
        migrations.AddField(
            model_name='section',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='section',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='longitude'),
        ),
        migrations.AddField(
            model_name='section',
            name='phone_1',
            field=models.CharField(blank=True, max_length=15, verbose_name='Phone 1'),
        ),
        migrations.AddField(
            model_name='section',
            name='phone_2',
            field=models.CharField(blank=True, max_length=15, verbose_name='Phone 2'),
        ),
        migrations.AddField(
            model_name='section',
            name='phone_3',
            field=models.CharField(blank=True, max_length=15, verbose_name='Phone 3'),
        ),
        migrations.AddField(
            model_name='section',
            name='twitter_url',
            field=models.URLField(blank=True, max_length=255, verbose_name='Twitter url'),
        ),
        migrations.AddField(
            model_name='section',
            name='web_site',
            field=models.CharField(blank=True, max_length=255, verbose_name='Web Site'),
        ),
        migrations.AddField(
            model_name='sectionphoto',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_photos', to='Regions.Section', verbose_name='Event'),
        ),
    ]
