# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-01 12:56
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Regions', '0010_auto_20161123_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='extra_data',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Extra Data'),
        ),
        migrations.AlterField(
            model_name='region',
            name='extra_data_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Extra Data'),
        ),
        migrations.AlterField(
            model_name='region',
            name='extra_data_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Extra Data'),
        ),
        migrations.AlterField(
            model_name='region',
            name='heading',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='region',
            name='heading_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='region',
            name='heading_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='region',
            name='sub_heading',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Sub Heading'),
        ),
        migrations.AlterField(
            model_name='region',
            name='sub_heading_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Sub Heading'),
        ),
        migrations.AlterField(
            model_name='region',
            name='sub_heading_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Sub Heading'),
        ),
        migrations.AlterField(
            model_name='region',
            name='sub_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Sub Title'),
        ),
        migrations.AlterField(
            model_name='region',
            name='sub_title_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Sub Title'),
        ),
        migrations.AlterField(
            model_name='region',
            name='sub_title_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Sub Title'),
        ),
        migrations.AlterField(
            model_name='section',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='section',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='section',
            name='content_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='section',
            name='sub_heading',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Sub Heading'),
        ),
        migrations.AlterField(
            model_name='section',
            name='sub_heading_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Sub Heading'),
        ),
        migrations.AlterField(
            model_name='section',
            name='sub_heading_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Sub Heading'),
        ),
        migrations.AlterField(
            model_name='section',
            name='sub_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Sub Title'),
        ),
        migrations.AlterField(
            model_name='section',
            name='sub_title_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Sub Title'),
        ),
        migrations.AlterField(
            model_name='section',
            name='sub_title_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Sub Title'),
        ),
    ]
