# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-07 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Regions', '0013_section_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='excerpt',
            field=models.TextField(default=0, verbose_name='excerpt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='excerpt_en',
            field=models.TextField(default=0, verbose_name='excerpt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='excerpt_fr',
            field=models.TextField(default=0, verbose_name='excerpt'),
            preserve_default=False,
        ),
    ]
