# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-07 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Regions', '0014_auto_20161207_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='excerpt',
            field=models.TextField(help_text='Excerpt to display on search results and short descriptions', verbose_name='excerpt'),
        ),
        migrations.AlterField(
            model_name='section',
            name='excerpt_en',
            field=models.TextField(help_text='Excerpt to display on search results and short descriptions', verbose_name='excerpt'),
        ),
        migrations.AlterField(
            model_name='section',
            name='excerpt_fr',
            field=models.TextField(help_text='Excerpt to display on search results and short descriptions', verbose_name='excerpt'),
        ),
    ]
