# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-20 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Regions', '0015_auto_20161207_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='button_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='button text'),
        ),
    ]
