# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-20 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Regions', '0016_region_button_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='button_text_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='button text'),
        ),
        migrations.AddField(
            model_name='region',
            name='button_text_fr',
            field=models.CharField(blank=True, max_length=255, verbose_name='button text'),
        ),
    ]
