# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-20 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Regions', '0017_auto_20161220_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='region',
        ),
        migrations.AddField(
            model_name='section',
            name='region',
            field=models.ManyToManyField(related_name='sections', to='Regions.Region'),
        ),
    ]
