# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-23 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Regions', '0018_auto_20161220_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ('order',), 'verbose_name': 'Regions Section', 'verbose_name_plural': 'Regions Sections'},
        ),
        migrations.AddField(
            model_name='section',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='order'),
        ),
    ]
