# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-14 21:22
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Regions', '0019_auto_20161223_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='subtitle',
            field=models.TextField(verbose_name='sub title'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='subtitle_en',
            field=models.TextField(verbose_name='sub title'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='subtitle_fr',
            field=models.TextField(verbose_name='sub title'),
        ),
        migrations.AlterField(
            model_name='region',
            name='sub_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Inner Banner Subtitle'),
        ),
        migrations.AlterField(
            model_name='region',
            name='sub_title_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Inner Banner Subtitle'),
        ),
        migrations.AlterField(
            model_name='region',
            name='sub_title_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Inner Banner Subtitle'),
        ),
    ]
