# Generated by Django 2.2.4 on 2019-09-11 13:45

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Regions', '0023_auto_20171024_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='meta_description_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='meta_keywords_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='sub_regions_heading_es',
            field=models.TextField(blank=True, null=True, verbose_name='Sub Regions Heading'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='sub_regions_image_alt_text_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt text'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='sub_regions_sub_heading_es',
            field=models.TextField(blank=True, null=True, verbose_name='Sub Regions Sub Heading'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='subtitle_es',
            field=models.TextField(null=True, verbose_name='sub title'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='title_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='region',
            name='button_text_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='button text'),
        ),
        migrations.AddField(
            model_name='region',
            name='extra_data_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Extra Data'),
        ),
        migrations.AddField(
            model_name='region',
            name='heading_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Heading'),
        ),
        migrations.AddField(
            model_name='region',
            name='meta_description_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='region',
            name='meta_keywords_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='region',
            name='slug_es',
            field=models.SlugField(max_length=255, null=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='region',
            name='sub_banner_image_alt_text_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt text'),
        ),
        migrations.AddField(
            model_name='region',
            name='sub_heading_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Sub Heading'),
        ),
        migrations.AddField(
            model_name='region',
            name='sub_title_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Inner Banner Subtitle'),
        ),
        migrations.AddField(
            model_name='region',
            name='title_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='section',
            name='button_text_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='button text'),
        ),
        migrations.AddField(
            model_name='section',
            name='content_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='section',
            name='excerpt_es',
            field=models.TextField(help_text='Excerpt to display on search results and short descriptions', null=True, verbose_name='excerpt'),
        ),
        migrations.AddField(
            model_name='section',
            name='meta_description_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='section',
            name='meta_keywords_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='section',
            name='slug_es',
            field=models.SlugField(max_length=255, null=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='section',
            name='sub_heading_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Sub Heading'),
        ),
        migrations.AddField(
            model_name='section',
            name='sub_title_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Sub Title'),
        ),
        migrations.AddField(
            model_name='section',
            name='title_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='sectionphoto',
            name='alt_text_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt text'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='banner_image',
            field=models.ImageField(upload_to='regions_banner', verbose_name='Banner image'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='meta_description_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='meta_description_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='meta_keywords_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='meta_keywords_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='sub_regions_heading_en',
            field=models.TextField(blank=True, null=True, verbose_name='Sub Regions Heading'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='sub_regions_heading_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Sub Regions Heading'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='sub_regions_image',
            field=models.ImageField(upload_to='sub_regions_image', verbose_name='Sub Regions image'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='sub_regions_image_alt_text_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt text'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='sub_regions_image_alt_text_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt text'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='sub_regions_sub_heading_en',
            field=models.TextField(blank=True, null=True, verbose_name='Sub Regions Sub Heading'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='sub_regions_sub_heading_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Sub Regions Sub Heading'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='subtitle_en',
            field=models.TextField(null=True, verbose_name='sub title'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='subtitle_fr',
            field=models.TextField(null=True, verbose_name='sub title'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='region',
            name='banner_image',
            field=models.ImageField(upload_to='region_banner', verbose_name='Banner image'),
        ),
        migrations.AlterField(
            model_name='region',
            name='button_text_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='button text'),
        ),
        migrations.AlterField(
            model_name='region',
            name='button_text_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='button text'),
        ),
        migrations.AlterField(
            model_name='region',
            name='extra_data_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Extra Data'),
        ),
        migrations.AlterField(
            model_name='region',
            name='extra_data_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Extra Data'),
        ),
        migrations.AlterField(
            model_name='region',
            name='heading_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='region',
            name='heading_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='region',
            name='meta_description_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='region',
            name='meta_description_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='region',
            name='meta_keywords_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='region',
            name='meta_keywords_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='region',
            name='slug_en',
            field=models.SlugField(max_length=255, null=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='region',
            name='slug_fr',
            field=models.SlugField(max_length=255, null=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='region',
            name='sub_banner_image',
            field=models.ImageField(upload_to='sub_region_banner', verbose_name='Sub Banner image'),
        ),
        migrations.AlterField(
            model_name='region',
            name='sub_banner_image_alt_text_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt text'),
        ),
        migrations.AlterField(
            model_name='region',
            name='sub_banner_image_alt_text_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt text'),
        ),
        migrations.AlterField(
            model_name='region',
            name='sub_heading_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Sub Heading'),
        ),
        migrations.AlterField(
            model_name='region',
            name='sub_heading_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Sub Heading'),
        ),
        migrations.AlterField(
            model_name='region',
            name='sub_title_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Inner Banner Subtitle'),
        ),
        migrations.AlterField(
            model_name='region',
            name='sub_title_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Inner Banner Subtitle'),
        ),
        migrations.AlterField(
            model_name='region',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='region',
            name='title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='section',
            name='banner_image',
            field=models.ImageField(upload_to='region_section_banner', verbose_name='Banner image'),
        ),
        migrations.AlterField(
            model_name='section',
            name='button_text_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='button text'),
        ),
        migrations.AlterField(
            model_name='section',
            name='button_text_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='button text'),
        ),
        migrations.AlterField(
            model_name='section',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='section',
            name='content_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='section',
            name='excerpt_en',
            field=models.TextField(help_text='Excerpt to display on search results and short descriptions', null=True, verbose_name='excerpt'),
        ),
        migrations.AlterField(
            model_name='section',
            name='excerpt_fr',
            field=models.TextField(help_text='Excerpt to display on search results and short descriptions', null=True, verbose_name='excerpt'),
        ),
        migrations.AlterField(
            model_name='section',
            name='meta_description_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='section',
            name='meta_description_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='section',
            name='meta_keywords_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='section',
            name='meta_keywords_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='section',
            name='slug_en',
            field=models.SlugField(max_length=255, null=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='section',
            name='slug_fr',
            field=models.SlugField(max_length=255, null=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='section',
            name='sub_heading_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Sub Heading'),
        ),
        migrations.AlterField(
            model_name='section',
            name='sub_heading_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Sub Heading'),
        ),
        migrations.AlterField(
            model_name='section',
            name='sub_title_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Sub Title'),
        ),
        migrations.AlterField(
            model_name='section',
            name='sub_title_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Sub Title'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='sectionphoto',
            name='alt_text_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt text'),
        ),
        migrations.AlterField(
            model_name='sectionphoto',
            name='alt_text_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt text'),
        ),
        migrations.AlterField(
            model_name='sectionphoto',
            name='image',
            field=models.ImageField(upload_to='region_section_photos', verbose_name='image'),
        ),
    ]
