# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-30 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('name_fr', models.CharField(max_length=255, verbose_name='name')),
                ('name_en', models.CharField(max_length=255, verbose_name='name')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'ordering': ('order',),
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('title_en', models.CharField(max_length=255, verbose_name='title')),
                ('title_fr', models.CharField(max_length=255, verbose_name='title')),
                ('excerpt', models.TextField(verbose_name='excerpt')),
                ('excerpt_fr', models.TextField(verbose_name='excerpt')),
                ('excerpt_en', models.TextField(verbose_name='excerpt')),
                ('banner_image', models.ImageField(upload_to=b'events_configuration', verbose_name='banner image')),
            ],
            options={
                'verbose_name': 'Configuration',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('title_fr', models.CharField(max_length=255, verbose_name='title')),
                ('title_en', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.SlugField(max_length=255, verbose_name='slug')),
                ('slug_en', models.SlugField(max_length=255, verbose_name='slug')),
                ('slug_fr', models.SlugField(max_length=255, verbose_name='slug')),
                ('subtitle', models.CharField(max_length=255, verbose_name='subtitle')),
                ('subtitle_en', models.CharField(max_length=255, verbose_name='subtitle')),
                ('subtitle_fr', models.CharField(max_length=255, verbose_name='subtitle')),
                ('excerpt', models.TextField(verbose_name='excerpt')),
                ('excerpt_en', models.TextField(verbose_name='excerpt')),
                ('excerpt_fr', models.TextField(verbose_name='excerpt')),
                ('content', models.TextField(verbose_name='content')),
                ('content_fr', models.TextField(verbose_name='content')),
                ('content_en', models.TextField(verbose_name='content')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('image', models.ImageField(upload_to=b'events', verbose_name='image')),
                ('banner_image', models.ImageField(upload_to=b'banner_events', verbose_name='banner image')),
                ('address', models.TextField(verbose_name='Address')),
                ('web_site', models.CharField(blank=True, max_length=255, verbose_name='Web Site')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Contact Email')),
                ('instagram_url', models.URLField(blank=True, max_length=255, verbose_name='Instagram url')),
                ('twitter_url', models.URLField(blank=True, max_length=255, verbose_name='Twitter url')),
                ('facebook_url', models.URLField(blank=True, max_length=255, verbose_name='Facebook url')),
                ('phone_1', models.CharField(blank=True, max_length=15, verbose_name='Phone 1')),
                ('phone_2', models.CharField(blank=True, max_length=15, verbose_name='Phone 2')),
                ('phone_3', models.CharField(blank=True, max_length=15, verbose_name='Phone 3')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='longitude')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('categories', models.ManyToManyField(related_name='events', to='Events.Category', verbose_name='categories')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='EventPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'event_photos', verbose_name='image')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_photos', to='Events.Event', verbose_name='Event')),
            ],
            options={
                'verbose_name': 'EventPhoto',
                'verbose_name_plural': 'Event Photos',
            },
        ),
    ]
