# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-16 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_initial_config'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventphoto',
            options={'ordering': ('order',), 'verbose_name': 'EventPhoto', 'verbose_name_plural': 'Event Photos'},
        ),
        migrations.AddField(
            model_name='eventphoto',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='order'),
        ),
    ]
