# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-22 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0004_auto_20161122_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
    ]
