# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-01 12:49
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0007_auto_20161123_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='event',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='event',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='event',
            name='content_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='content'),
        ),
    ]
