# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-24 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0011_metafields_translate'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventphoto',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Alt text'),
        ),
        migrations.AddField(
            model_name='eventphoto',
            name='alt_text_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Alt text'),
        ),
        migrations.AddField(
            model_name='eventphoto',
            name='alt_text_fr',
            field=models.CharField(blank=True, max_length=255, verbose_name='Alt text'),
        ),
    ]
