# Generated by Django 2.2.4 on 2019-09-11 13:45

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0013_auto_20171024_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_es',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='excerpt_es',
            field=models.TextField(null=True, verbose_name='sub title'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='meta_description_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='meta_keywords_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='title_es',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='event',
            name='content_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='event',
            name='excerpt_es',
            field=models.TextField(null=True, verbose_name='excerpt'),
        ),
        migrations.AddField(
            model_name='event',
            name='image_alt_text_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt Text'),
        ),
        migrations.AddField(
            model_name='event',
            name='meta_description_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='meta_keywords_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='event',
            name='slug_es',
            field=models.SlugField(max_length=255, null=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='event',
            name='subtitle_es',
            field=models.CharField(max_length=255, null=True, verbose_name='subtitle'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_es',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='eventphoto',
            name='alt_text_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt text'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='banner_image',
            field=models.ImageField(upload_to='events_configuration', verbose_name='banner image'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='excerpt_en',
            field=models.TextField(null=True, verbose_name='sub title'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='excerpt_fr',
            field=models.TextField(null=True, verbose_name='sub title'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='meta_description_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='meta_description_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='meta_keywords_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='meta_keywords_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='event',
            name='banner_image',
            field=models.ImageField(upload_to='banner_events', verbose_name='banner image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='event',
            name='content_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='event',
            name='excerpt_en',
            field=models.TextField(null=True, verbose_name='excerpt'),
        ),
        migrations.AlterField(
            model_name='event',
            name='excerpt_fr',
            field=models.TextField(null=True, verbose_name='excerpt'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to='events', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image_alt_text_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt Text'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image_alt_text_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt Text'),
        ),
        migrations.AlterField(
            model_name='event',
            name='meta_description_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='meta_description_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='meta_keywords_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='event',
            name='meta_keywords_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug_en',
            field=models.SlugField(max_length=255, null=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug_fr',
            field=models.SlugField(max_length=255, null=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='event',
            name='subtitle_en',
            field=models.CharField(max_length=255, null=True, verbose_name='subtitle'),
        ),
        migrations.AlterField(
            model_name='event',
            name='subtitle_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='subtitle'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='eventphoto',
            name='alt_text_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt text'),
        ),
        migrations.AlterField(
            model_name='eventphoto',
            name='alt_text_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt text'),
        ),
        migrations.AlterField(
            model_name='eventphoto',
            name='image',
            field=models.ImageField(upload_to='event_photos', verbose_name='image'),
        ),
    ]
