# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-03 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('image', models.FileField(help_text='Color svg file', upload_to=b'images/footer', verbose_name='icon')),
                ('url', models.URLField(blank=True, max_length=255, verbose_name='link url')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='order')),
                ('display', models.BooleanField(default=True, verbose_name='display')),
            ],
            options={
                'ordering': ('order',),
                'verbose_name': 'Footer Logo Link',
                'verbose_name_plural': 'Footer Logo Links',
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='link')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='order')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'ordering': ('order',),
                'verbose_name': 'Footer Link',
                'verbose_name_plural': 'Footer Links',
            },
        ),
        migrations.CreateModel(
            name='FooterSubLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('link', models.CharField(max_length=255, verbose_name='link')),
                ('new_window', models.BooleanField(default=False, verbose_name='open in new window')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='order')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('main_menu_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sublinks', to='Menus.FooterLink', verbose_name='main menu link')),
            ],
            options={
                'ordering': ('order',),
                'verbose_name': 'Footer SubLink',
                'verbose_name_plural': 'Footer SubLinks',
            },
        ),
    ]
