# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-12 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerlink',
            name='link_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='link'),
        ),
        migrations.AddField(
            model_name='footerlink',
            name='link_fr',
            field=models.CharField(blank=True, max_length=255, verbose_name='link'),
        ),
        migrations.AddField(
            model_name='footerlink',
            name='title_en',
            field=models.CharField(default=1, max_length=255, verbose_name='title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footerlink',
            name='title_fr',
            field=models.CharField(default=1, max_length=255, verbose_name='title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footersublink',
            name='link_en',
            field=models.CharField(default=1, max_length=255, verbose_name='link'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footersublink',
            name='link_fr',
            field=models.CharField(default=1, max_length=255, verbose_name='link'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footersublink',
            name='title_en',
            field=models.CharField(default=1, max_length=255, verbose_name='title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footersublink',
            name='title_fr',
            field=models.CharField(default=1, max_length=255, verbose_name='title'),
            preserve_default=False,
        ),
    ]
