# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-24 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menus', '0002_auto_20161212_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externallink',
            name='image',
            field=models.FileField(help_text='Color svg file', upload_to=b'images\\footer', verbose_name='icon'),
        ),
    ]
