# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-08-13 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menus', '0003_auto_20171024_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externallink',
            name='image',
            field=models.FileField(help_text='Color svg file', upload_to=b'images/footer', verbose_name='icon'),
        ),
    ]
