# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-07-18 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menus', '0004_auto_20180813_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externallink',
            name='image',
            field=models.FileField(help_text='Color svg file', upload_to=b'images\\footer', verbose_name='icon'),
        ),
    ]
