# Generated by Django 2.2.4 on 2019-09-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menus', '0005_auto_20190718_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerlink',
            name='link_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='link'),
        ),
        migrations.AddField(
            model_name='footerlink',
            name='title_es',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='footersublink',
            name='link_es',
            field=models.CharField(max_length=255, null=True, verbose_name='link'),
        ),
        migrations.AddField(
            model_name='footersublink',
            name='title_es',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='externallink',
            name='image',
            field=models.FileField(help_text='Color svg file', upload_to='images\\footer', verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='link_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='link_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='footersublink',
            name='link_en',
            field=models.CharField(max_length=255, null=True, verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='footersublink',
            name='link_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='footersublink',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='footersublink',
            name='title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
    ]
