# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-26 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('title_fr', models.CharField(max_length=255, verbose_name='Title')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title')),
                ('subtitle', models.TextField(verbose_name='Description')),
                ('subtitle_en', models.TextField(verbose_name='Description')),
                ('subtitle_fr', models.TextField(verbose_name='Description')),
                ('banner_image', models.ImageField(upload_to=b'visitor_banner', verbose_name='Banner image')),
                ('location_description', models.TextField(verbose_name='Location description')),
                ('location_description_fr', models.TextField(verbose_name='Location description')),
                ('location_description_en', models.TextField(verbose_name='Location description')),
                ('sub_heading', models.TextField(blank=True, verbose_name='Sub Heading')),
                ('sub_heading_en', models.TextField(blank=True, verbose_name='Sub Heading')),
                ('sub_heading_fr', models.TextField(blank=True, verbose_name='Sub Heading')),
                ('location_image', models.ImageField(upload_to=b'visitor_location', verbose_name='Location image')),
                ('arrive_description', models.TextField(verbose_name='Arrive description')),
                ('arrive_description_en', models.TextField(verbose_name='Arrive description')),
                ('arrive_description_fr', models.TextField(verbose_name='Arrive description')),
                ('background_arrive_image', models.ImageField(upload_to=b'visitor_arrive_background', verbose_name='Background arrive image')),
                ('weather_description', models.TextField(blank=True, verbose_name='Weather description')),
                ('weather_description_fr', models.TextField(blank=True, verbose_name='Weather description')),
                ('weather_description_en', models.TextField(blank=True, verbose_name='Weather description')),
            ],
            options={
                'verbose_name': 'Visitor Guide Configuration',
            },
        ),
        migrations.CreateModel(
            name='QueretaroLanding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('title_fr', models.CharField(max_length=255, verbose_name='Title')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title')),
                ('excerpt', models.TextField(verbose_name='Excerpt')),
                ('excerpt_fr', models.TextField(verbose_name='Excerpt')),
                ('excerpt_en', models.TextField(verbose_name='Excerpt')),
                ('banner_image', models.ImageField(upload_to=b'queretaro_landing_banner', verbose_name='Banner image')),
                ('heading', models.TextField(verbose_name='Location description')),
                ('heading_en', models.TextField(verbose_name='Location description')),
                ('heading_fr', models.TextField(verbose_name='Location description')),
                ('description', models.TextField(verbose_name='Sub Heading')),
                ('description_en', models.TextField(verbose_name='Sub Heading')),
                ('description_fr', models.TextField(verbose_name='Sub Heading')),
                ('image', models.ImageField(upload_to=b'visitor_location', verbose_name='Location image')),
            ],
            options={
                'verbose_name': 'Queretaro Landing',
            },
        ),
        migrations.CreateModel(
            name='QueretaroSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('title_fr', models.CharField(max_length=255, verbose_name='Title')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title')),
                ('sub_title', models.TextField(verbose_name='Sub Title')),
                ('sub_title_fr', models.TextField(verbose_name='Sub Title')),
                ('sub_title_en', models.TextField(verbose_name='Sub Title')),
                ('excerpt', models.TextField(verbose_name='Excerpt')),
                ('excerpt_fr', models.TextField(verbose_name='Excerpt')),
                ('excerpt_en', models.TextField(verbose_name='Excerpt')),
                ('banner_image', models.ImageField(upload_to=b'queretaro_section_banner', verbose_name='Banner image')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Visitor.QueretaroLanding')),
            ],
            options={
                'verbose_name': 'Queretaro Section',
                'verbose_name_plural': 'Queretaro Sections',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title')),
                ('title_fr', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_en', models.TextField(verbose_name='Description')),
                ('description_fr', models.TextField(verbose_name='Description')),
                ('icon', models.CharField(choices=[(b'qro-travel-icon-winter', 'Winter'), (b'qro-travel-icon-spring', 'Spring'), (b'qro-travel-icon-summer', 'Summer'), (b'qro-travel-icon-autumn', 'Autumn')], default=b'qro-travel-icon-winter', max_length=40, verbose_name='Icon')),
                ('image', models.ImageField(upload_to=b'visitor_seasons', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Visitor Guide Season',
                'verbose_name_plural': 'Visitor Guide Seasons',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('title_fr', models.CharField(max_length=255, verbose_name='Title')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title')),
                ('sub_title', models.TextField(verbose_name='Sub Title')),
                ('sub_title_en', models.TextField(verbose_name='Sub Title')),
                ('sub_title_fr', models.TextField(verbose_name='Sub Title')),
                ('heading', models.CharField(max_length=255, verbose_name='Heading')),
                ('heading_en', models.CharField(max_length=255, verbose_name='Heading')),
                ('heading_fr', models.CharField(max_length=255, verbose_name='Heading')),
                ('sub_heading', models.TextField(verbose_name='Sub Heading')),
                ('sub_heading_en', models.TextField(verbose_name='Sub Heading')),
                ('sub_heading_fr', models.TextField(verbose_name='Sub Heading')),
                ('banner_image', models.ImageField(upload_to=b'visitor_section_banner', verbose_name='Banner image')),
                ('section_file', models.FileField(blank=True, null=True, upload_to=b'visitor_section_file', verbose_name='Section file')),
                ('button_section_text', models.CharField(blank=True, max_length=255, verbose_name='Button Section Text')),
                ('button_section_text_en', models.CharField(blank=True, max_length=255, verbose_name='Button Section Text')),
                ('button_section_text_fr', models.CharField(blank=True, max_length=255, verbose_name='Button Section Text')),
            ],
            options={
                'verbose_name': 'Visitor Guide Section',
                'verbose_name_plural': 'Visitor Guide Sections',
            },
        ),
        migrations.CreateModel(
            name='TransportationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title')),
                ('title_fr', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_en', models.TextField(verbose_name='Description')),
                ('description_fr', models.TextField(verbose_name='Description')),
                ('icon', models.CharField(choices=[(b'qro-travel-icon-plane', 'Airplane'), (b'qro-travel-icon-bus', 'Bus'), (b'qro-travel-icon-auto', 'Automobile'), (b'qro-travel-icon-taxi', 'Taxi')], default=b'qro-travel-icon-plane', max_length=40, verbose_name='Icon')),
                ('image', models.ImageField(upload_to=b'visitor_transportation_types', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Visitor Guide Transportation Type',
                'verbose_name_plural': 'Visitor Guide Transportation Types',
            },
        ),
    ]
