# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-03 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visitor', '0002_initial_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='sub_heading_title',
            field=models.TextField(blank=True, verbose_name='Sub Heading Title'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='sub_heading_title_en',
            field=models.TextField(blank=True, verbose_name='Sub Heading Title'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='sub_heading_title_fr',
            field=models.TextField(blank=True, verbose_name='Sub Heading Title'),
        ),
    ]
