# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-03 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visitor', '0003_auto_20161103_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='sub_heading_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Sub Heading Title'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='sub_heading_title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Sub Heading Title'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='sub_heading_title_fr',
            field=models.CharField(blank=True, max_length=255, verbose_name='Sub Heading Title'),
        ),
    ]
