# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-16 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visitor', '0004_auto_20161103_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queretarosection',
            options={'ordering': ('order',), 'verbose_name': 'Queretaro Section', 'verbose_name_plural': 'Queretaro Sections'},
        ),
        migrations.RemoveField(
            model_name='queretarosection',
            name='configuration',
        ),
        migrations.AddField(
            model_name='queretarosection',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='order'),
        ),
    ]
