# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-16 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visitor', '0005_auto_20161116_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='queretarosection',
            name='button_link',
            field=models.CharField(blank=True, max_length=255, verbose_name='button link'),
        ),
        migrations.AddField(
            model_name='queretarosection',
            name='button_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='button text'),
        ),
        migrations.AddField(
            model_name='queretarosection',
            name='button_text_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='button text'),
        ),
        migrations.AddField(
            model_name='queretarosection',
            name='button_text_fr',
            field=models.CharField(blank=True, max_length=255, verbose_name='button text'),
        ),
    ]
