# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-18 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visitor', '0006_auto_20161116_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='queretarolanding',
            name='faqs_text',
            field=models.TextField(blank=True, verbose_name='FAQs text'),
        ),
        migrations.AddField(
            model_name='queretarolanding',
            name='show_faqs_text',
            field=models.BooleanField(default=True, verbose_name='Show faqs text'),
            preserve_default=False,
        ),
    ]
