# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-22 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visitor', '0009_configuration_section_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='section_name_en',
            field=models.CharField(default=1, max_length=255, verbose_name='Section name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuration',
            name='section_name_fr',
            field=models.CharField(default=1, max_length=255, verbose_name='Section name'),
            preserve_default=False,
        ),
    ]
