# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-01 12:56
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Visitor', '0010_auto_20161122_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='sub_heading',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Sub Heading'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='sub_heading_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Sub Heading'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='sub_heading_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Sub Heading'),
        ),
        migrations.AlterField(
            model_name='queretarolanding',
            name='faqs_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='FAQs text'),
        ),
        migrations.AlterField(
            model_name='queretarolanding',
            name='faqs_text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='FAQs text'),
        ),
        migrations.AlterField(
            model_name='queretarolanding',
            name='faqs_text_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='FAQs text'),
        ),
        migrations.AlterField(
            model_name='queretarosection',
            name='excerpt',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Excerpt'),
        ),
        migrations.AlterField(
            model_name='queretarosection',
            name='excerpt_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Excerpt'),
        ),
        migrations.AlterField(
            model_name='queretarosection',
            name='excerpt_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Excerpt'),
        ),
        migrations.AlterField(
            model_name='queretarosection',
            name='sub_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Sub Title'),
        ),
        migrations.AlterField(
            model_name='queretarosection',
            name='sub_title_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Sub Title'),
        ),
        migrations.AlterField(
            model_name='queretarosection',
            name='sub_title_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Sub Title'),
        ),
        migrations.AlterField(
            model_name='section',
            name='sub_heading',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Sub Heading'),
        ),
        migrations.AlterField(
            model_name='section',
            name='sub_heading_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Sub Heading'),
        ),
        migrations.AlterField(
            model_name='section',
            name='sub_heading_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Sub Heading'),
        ),
    ]
