# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-12 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visitor', '0012_queretarosection_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='queretarosection',
            name='button_link_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='button link'),
        ),
        migrations.AddField(
            model_name='queretarosection',
            name='button_link_fr',
            field=models.CharField(blank=True, max_length=255, verbose_name='button link'),
        ),
    ]
