# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-14 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visitor', '0013_auto_20161212_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queretarolanding',
            name='banner_image',
            field=models.ImageField(upload_to=b'queretaro_landing_banner', verbose_name='Image of the Queretaro banner'),
        ),
        migrations.AlterField(
            model_name='queretarolanding',
            name='excerpt',
            field=models.TextField(verbose_name='sub title'),
        ),
        migrations.AlterField(
            model_name='queretarolanding',
            name='excerpt_en',
            field=models.TextField(verbose_name='sub title'),
        ),
        migrations.AlterField(
            model_name='queretarolanding',
            name='excerpt_fr',
            field=models.TextField(verbose_name='sub title'),
        ),
    ]
