# Generated by Django 2.2.4 on 2019-09-11 13:45

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Visitor', '0016_metafields_translate'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='arrive_description_es',
            field=models.TextField(null=True, verbose_name='Arrive description'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='location_description_es',
            field=models.TextField(null=True, verbose_name='Location description'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='meta_description_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='meta_keywords_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='section_name_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Section name'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='sub_heading_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Sub Heading'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='sub_heading_title_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sub Heading Title'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='subtitle_es',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='title_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='weather_description_es',
            field=models.TextField(blank=True, null=True, verbose_name='Weather description'),
        ),
        migrations.AddField(
            model_name='queretarolanding',
            name='description_es',
            field=models.TextField(null=True, verbose_name='Sub Heading'),
        ),
        migrations.AddField(
            model_name='queretarolanding',
            name='excerpt_es',
            field=models.TextField(null=True, verbose_name='sub title'),
        ),
        migrations.AddField(
            model_name='queretarolanding',
            name='faqs_text_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='FAQs text'),
        ),
        migrations.AddField(
            model_name='queretarolanding',
            name='heading_es',
            field=models.TextField(null=True, verbose_name='Location description'),
        ),
        migrations.AddField(
            model_name='queretarolanding',
            name='meta_description_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='queretarolanding',
            name='meta_keywords_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='queretarolanding',
            name='title_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='queretarosection',
            name='button_link_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='button link'),
        ),
        migrations.AddField(
            model_name='queretarosection',
            name='button_text_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='button text'),
        ),
        migrations.AddField(
            model_name='queretarosection',
            name='excerpt_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Excerpt'),
        ),
        migrations.AddField(
            model_name='queretarosection',
            name='sub_title_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Sub Title'),
        ),
        migrations.AddField(
            model_name='queretarosection',
            name='title_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='season',
            name='description_es',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='season',
            name='title_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='section',
            name='button_section_text_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Button Section Text'),
        ),
        migrations.AddField(
            model_name='section',
            name='heading_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Heading'),
        ),
        migrations.AddField(
            model_name='section',
            name='sub_heading_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Sub Heading'),
        ),
        migrations.AddField(
            model_name='section',
            name='sub_title_es',
            field=models.TextField(null=True, verbose_name='Sub Title'),
        ),
        migrations.AddField(
            model_name='section',
            name='title_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='transportationtype',
            name='description_es',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='transportationtype',
            name='title_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='arrive_description_en',
            field=models.TextField(null=True, verbose_name='Arrive description'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='arrive_description_fr',
            field=models.TextField(null=True, verbose_name='Arrive description'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='background_arrive_image',
            field=models.ImageField(upload_to='visitor_arrive_background', verbose_name='Background arrive image'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='banner_image',
            field=models.ImageField(upload_to='visitor_banner', verbose_name='Banner image'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='location_description_en',
            field=models.TextField(null=True, verbose_name='Location description'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='location_description_fr',
            field=models.TextField(null=True, verbose_name='Location description'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='location_image',
            field=models.ImageField(upload_to='visitor_location', verbose_name='Location image'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='meta_description_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='meta_description_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='meta_keywords_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='meta_keywords_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='section_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Section name'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='section_name_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Section name'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='sub_heading_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Sub Heading'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='sub_heading_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Sub Heading'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='sub_heading_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sub Heading Title'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='sub_heading_title_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sub Heading Title'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='subtitle_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='subtitle_fr',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='weather_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Weather description'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='weather_description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Weather description'),
        ),
        migrations.AlterField(
            model_name='queretarolanding',
            name='banner_image',
            field=models.ImageField(upload_to='queretaro_landing_banner', verbose_name='Image of the Queretaro banner'),
        ),
        migrations.AlterField(
            model_name='queretarolanding',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Sub Heading'),
        ),
        migrations.AlterField(
            model_name='queretarolanding',
            name='description_fr',
            field=models.TextField(null=True, verbose_name='Sub Heading'),
        ),
        migrations.AlterField(
            model_name='queretarolanding',
            name='excerpt_en',
            field=models.TextField(null=True, verbose_name='sub title'),
        ),
        migrations.AlterField(
            model_name='queretarolanding',
            name='excerpt_fr',
            field=models.TextField(null=True, verbose_name='sub title'),
        ),
        migrations.AlterField(
            model_name='queretarolanding',
            name='faqs_text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='FAQs text'),
        ),
        migrations.AlterField(
            model_name='queretarolanding',
            name='faqs_text_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='FAQs text'),
        ),
        migrations.AlterField(
            model_name='queretarolanding',
            name='heading_en',
            field=models.TextField(null=True, verbose_name='Location description'),
        ),
        migrations.AlterField(
            model_name='queretarolanding',
            name='heading_fr',
            field=models.TextField(null=True, verbose_name='Location description'),
        ),
        migrations.AlterField(
            model_name='queretarolanding',
            name='image',
            field=models.ImageField(upload_to='visitor_location', verbose_name='Location image'),
        ),
        migrations.AlterField(
            model_name='queretarolanding',
            name='meta_description_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='queretarolanding',
            name='meta_description_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='queretarolanding',
            name='meta_keywords_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='queretarolanding',
            name='meta_keywords_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='queretarolanding',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='queretarolanding',
            name='title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='queretarosection',
            name='banner_image',
            field=models.ImageField(upload_to='queretaro_section_banner', verbose_name='Banner image'),
        ),
        migrations.AlterField(
            model_name='queretarosection',
            name='button_link_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='button link'),
        ),
        migrations.AlterField(
            model_name='queretarosection',
            name='button_link_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='button link'),
        ),
        migrations.AlterField(
            model_name='queretarosection',
            name='button_text_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='button text'),
        ),
        migrations.AlterField(
            model_name='queretarosection',
            name='button_text_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='button text'),
        ),
        migrations.AlterField(
            model_name='queretarosection',
            name='excerpt_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Excerpt'),
        ),
        migrations.AlterField(
            model_name='queretarosection',
            name='excerpt_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Excerpt'),
        ),
        migrations.AlterField(
            model_name='queretarosection',
            name='sub_title_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Sub Title'),
        ),
        migrations.AlterField(
            model_name='queretarosection',
            name='sub_title_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Sub Title'),
        ),
        migrations.AlterField(
            model_name='queretarosection',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='queretarosection',
            name='title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='season',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='season',
            name='description_fr',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='season',
            name='icon',
            field=models.CharField(choices=[('qro-travel-icon-winter', 'Winter'), ('qro-travel-icon-spring', 'Spring'), ('qro-travel-icon-summer', 'Summer'), ('qro-travel-icon-autumn', 'Autumn')], default='qro-travel-icon-winter', max_length=40, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='season',
            name='image',
            field=models.ImageField(upload_to='visitor_seasons', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='season',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='season',
            name='title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='section',
            name='banner_image',
            field=models.ImageField(upload_to='visitor_section_banner', verbose_name='Banner image'),
        ),
        migrations.AlterField(
            model_name='section',
            name='button_section_text_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Button Section Text'),
        ),
        migrations.AlterField(
            model_name='section',
            name='button_section_text_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Button Section Text'),
        ),
        migrations.AlterField(
            model_name='section',
            name='heading_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='section',
            name='heading_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_file',
            field=models.FileField(blank=True, null=True, upload_to='visitor_section_file', verbose_name='Section file'),
        ),
        migrations.AlterField(
            model_name='section',
            name='sub_heading_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Sub Heading'),
        ),
        migrations.AlterField(
            model_name='section',
            name='sub_heading_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Sub Heading'),
        ),
        migrations.AlterField(
            model_name='section',
            name='sub_title_en',
            field=models.TextField(null=True, verbose_name='Sub Title'),
        ),
        migrations.AlterField(
            model_name='section',
            name='sub_title_fr',
            field=models.TextField(null=True, verbose_name='Sub Title'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='transportationtype',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='transportationtype',
            name='description_fr',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='transportationtype',
            name='icon',
            field=models.CharField(choices=[('qro-travel-icon-plane', 'Airplane'), ('qro-travel-icon-bus', 'Bus'), ('qro-travel-icon-auto', 'Automobile'), ('qro-travel-icon-taxi', 'Taxi')], default='qro-travel-icon-plane', max_length=40, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='transportationtype',
            name='image',
            field=models.ImageField(upload_to='visitor_transportation_types', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='transportationtype',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='transportationtype',
            name='title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
    ]
