# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-30 01:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('name_fr', models.CharField(max_length=255, verbose_name='Name')),
                ('name_en', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title')),
                ('title_fr', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_en', models.TextField(verbose_name='Description')),
                ('description_fr', models.TextField(verbose_name='Description')),
                ('banner_image', models.ImageField(upload_to=b'contact', verbose_name='Banner Image')),
            ],
            options={
                'verbose_name': 'Configuration',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('title_fr', models.CharField(max_length=255, verbose_name='Title')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('answer_fr', models.TextField(verbose_name='Answer')),
                ('answer_en', models.TextField(verbose_name='Answer')),
                ('display', models.BooleanField(default=True, verbose_name='Display')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='FAQ.Category', verbose_name='Category')),
            ],
            options={
                'ordering': ('order', 'title'),
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
    ]
