# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-18 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0002_auto_20161018_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default=0, max_length=255, verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.CharField(default=0, max_length=255, verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='description_fr',
            field=models.CharField(default=0, max_length=255, verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=0, max_length=255, verbose_name='slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='slug_en',
            field=models.SlugField(default=0, max_length=255, verbose_name='slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='slug_fr',
            field=models.SlugField(default=0, max_length=255, verbose_name='slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_fr',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
    ]
