# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-14 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0004_auto_20161018_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='description',
            field=models.TextField(verbose_name='sub title'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='description_en',
            field=models.TextField(verbose_name='sub title'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='description_fr',
            field=models.TextField(verbose_name='sub title'),
        ),
    ]
