# Generated by Django 2.2.4 on 2019-09-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0007_metafields_translate'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_es',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_es',
            field=models.SlugField(max_length=255, null=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='description_es',
            field=models.TextField(null=True, verbose_name='sub title'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='meta_description_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='meta_keywords_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='title_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_es',
            field=models.TextField(null=True, verbose_name='Answer'),
        ),
        migrations.AddField(
            model_name='question',
            name='title_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug_en',
            field=models.SlugField(max_length=255, null=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug_fr',
            field=models.SlugField(max_length=255, null=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='banner_image',
            field=models.ImageField(upload_to='contact', verbose_name='Banner Image'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='description_en',
            field=models.TextField(null=True, verbose_name='sub title'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='description_fr',
            field=models.TextField(null=True, verbose_name='sub title'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='meta_description_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='meta_description_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='meta_keywords_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='meta_keywords_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_en',
            field=models.TextField(null=True, verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_fr',
            field=models.TextField(null=True, verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
    ]
