# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-30 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='Display name on this page.', max_length=255, verbose_name='Display Name')),
                ('screen_name', models.CharField(help_text='Facebook page name, found in URL', max_length=255, verbose_name='Screen Name')),
            ],
            options={
                'verbose_name': 'Facebook Account',
                'verbose_name_plural': 'Facebook Accounts',
            },
        ),
        migrations.CreateModel(
            name='FacebookConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=255, verbose_name='Client ID')),
                ('app_secret_key', models.CharField(max_length=255, verbose_name='App Secret Key')),
            ],
            options={
                'verbose_name': 'Facebook App Configuration',
            },
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
                ('image', models.ImageField(blank=True, upload_to=b'feeds', verbose_name='Image')),
                ('media_url', models.URLField(blank=True, verbose_name='Media Url')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='Link')),
                ('feeds_type', models.CharField(choices=[(b'twitter', 'twitter'), (b'instagram', 'instagram'), (b'facebook', 'facebook')], default=b'facebook', max_length=20, verbose_name='Feeds type')),
                ('uid', models.CharField(blank=True, max_length=255, verbose_name='Uid')),
                ('publish_date', models.DateTimeField(blank=True, null=True, verbose_name='Publish Date')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
            options={
                'ordering': ['publish_date'],
                'verbose_name': 'Feed',
                'verbose_name_plural': 'Feeds',
            },
        ),
        migrations.CreateModel(
            name='InstagramAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='Display name on this page.', max_length=255, verbose_name='Display Name')),
            ],
            options={
                'verbose_name': 'Instagram Account',
                'verbose_name_plural': 'Instagram Accounts',
            },
        ),
        migrations.CreateModel(
            name='TwitterAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='Display name on this page.', max_length=255, verbose_name='Display Name')),
                ('username', models.CharField(max_length=255, verbose_name='Twitter Username')),
                ('oauth_token', models.CharField(max_length=255, verbose_name='OAuth Token')),
                ('oauth_secret', models.CharField(max_length=255, verbose_name='OAuth Secret')),
                ('twitter_key', models.CharField(max_length=255, verbose_name='Twitter Key')),
                ('twitter_key_secret', models.CharField(max_length=255, verbose_name='Twitter Key Secret')),
            ],
            options={
                'verbose_name': 'Twitter Account',
                'verbose_name_plural': 'Twitter Accounts',
            },
        ),
    ]
