# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-11 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialAccounts', '0003_feed_account_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='profile_img',
            field=models.URLField(blank=True, verbose_name='Profile image'),
        ),
    ]
