# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-05 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialAccounts', '0004_feed_profile_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feed',
            options={'ordering': ['-publish_date'], 'verbose_name': 'Feed', 'verbose_name_plural': 'Feeds'},
        ),
        migrations.AddField(
            model_name='feed',
            name='blank',
            field=models.BooleanField(default=False, help_text='Open link in another tab', verbose_name='Target Blank'),
        ),
    ]
