# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-08-13 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialAccounts', '0005_auto_20161205_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramaccount',
            name='access_token',
            field=models.CharField(default='', max_length=255, verbose_name='access token'),
            preserve_default=False,
        ),
    ]
