# Generated by Django 2.2.4 on 2019-09-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialAccounts', '0006_instagramaccount_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='feeds_type',
            field=models.CharField(choices=[('twitter', 'twitter'), ('instagram', 'instagram'), ('facebook', 'facebook')], default='facebook', max_length=20, verbose_name='Feeds type'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='image',
            field=models.ImageField(blank=True, upload_to='feeds', verbose_name='Image'),
        ),
    ]
