# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-30 02:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('name_fr', models.CharField(max_length=255, verbose_name='name')),
                ('name_en', models.CharField(max_length=255, verbose_name='name')),
                ('slug', models.SlugField(max_length=255, verbose_name='slug')),
                ('slug_en', models.SlugField(max_length=255, verbose_name='slug')),
                ('slug_fr', models.SlugField(max_length=255, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Configuration',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('title_fr', models.CharField(max_length=255, verbose_name='title')),
                ('title_en', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.SlugField(max_length=255, verbose_name='slug')),
                ('slug_en', models.SlugField(max_length=255, verbose_name='slug')),
                ('slug_fr', models.SlugField(max_length=255, verbose_name='slug')),
                ('subtitle', models.CharField(max_length=255, verbose_name='sub title')),
                ('subtitle_en', models.CharField(max_length=255, verbose_name='sub title')),
                ('subtitle_fr', models.CharField(max_length=255, verbose_name='sub title')),
                ('excerpt', models.TextField(verbose_name='excerpt')),
                ('excerpt_en', models.TextField(verbose_name='excerpt')),
                ('excerpt_fr', models.TextField(verbose_name='excerpt')),
                ('content', models.TextField(verbose_name='content')),
                ('content_fr', models.TextField(verbose_name='content')),
                ('content_en', models.TextField(verbose_name='content')),
                ('banner_image', models.ImageField(upload_to=b'banner_posts', verbose_name='banner image')),
                ('post_image', models.ImageField(upload_to=b'posts', verbose_name='post image')),
                ('publish_date', models.DateField(verbose_name='publish date')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='Blog.Category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.AddField(
            model_name='configuration',
            name='outstanding_post',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Blog.Post', verbose_name='Post'),
        ),
    ]
