# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-01 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20161201_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='banner_image',
            field=models.ImageField(default=1, upload_to=b'banner_categories_posts', verbose_name='banner image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuration',
            name='categories_title',
            field=models.CharField(default=1, max_length=255, verbose_name='categories title'),
            preserve_default=False,
        ),
    ]
