# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-01 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_auto_20161201_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='categories_title_en',
            field=models.CharField(default=1, max_length=255, verbose_name='categories title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuration',
            name='categories_title_fr',
            field=models.CharField(default=1, max_length=255, verbose_name='categories title'),
            preserve_default=False,
        ),
    ]
