# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-01 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_auto_20161201_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default=1, verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(default=1, verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='description_fr',
            field=models.TextField(default=1, verbose_name='description'),
            preserve_default=False,
        ),
    ]
