# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-01 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_auto_20161201_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='thumbnail_image',
            field=models.ImageField(default=1, upload_to=b'thumbnail_categories_posts', verbose_name='banner image'),
            preserve_default=False,
        ),
    ]
