# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-05 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_category_thumbnail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='thumbnail_image',
            field=models.ImageField(upload_to=b'thumbnail_categories_posts', verbose_name='thumbnail image'),
        ),
    ]
