# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-14 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0010_post_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterField(
            model_name='configuration',
            name='categories_title',
            field=models.CharField(max_length=255, verbose_name='Header of Featured Articles'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='categories_title_en',
            field=models.CharField(max_length=255, verbose_name='Header of Featured Articles'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='categories_title_fr',
            field=models.CharField(max_length=255, verbose_name='Header of Featured Articles'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='category_title',
            field=models.CharField(max_length=255, verbose_name='Categories Header'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='category_title_en',
            field=models.CharField(max_length=255, verbose_name='Categories Header'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='category_title_fr',
            field=models.CharField(max_length=255, verbose_name='Categories Header'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='outstanding_post',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Blog.Post', verbose_name='Outstanding Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(upload_to=b'posts', verbose_name='Content Image'),
        ),
    ]
