# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-16 12:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0011_auto_20170214_1917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
    ]
