# Generated by Django 2.2.4 on 2019-09-11 13:45

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0015_auto_20171024_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_es',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_keywords_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_es',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_es',
            field=models.SlugField(max_length=255, null=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='category',
            name='thumbnail_image_alt_text_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt text'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='categories_title_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Header of Featured Articles'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='category_title_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Categories Header'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='meta_description_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='meta_keywords_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt_es',
            field=models.TextField(null=True, verbose_name='excerpt'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_description_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_keywords_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_image_alt_text_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt text'),
        ),
        migrations.AddField(
            model_name='post',
            name='slug_es',
            field=models.SlugField(max_length=255, null=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='post',
            name='subtitle_es',
            field=models.CharField(max_length=255, null=True, verbose_name='sub title'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_es',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='category',
            name='banner_image',
            field=models.ImageField(upload_to='banner_categories_posts', verbose_name='banner image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description_fr',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_description_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_description_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_keywords_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_keywords_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug_en',
            field=models.SlugField(max_length=255, null=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug_fr',
            field=models.SlugField(max_length=255, null=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='category',
            name='thumbnail_image',
            field=models.ImageField(upload_to='thumbnail_categories_posts', verbose_name='thumbnail image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='thumbnail_image_alt_text_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt text'),
        ),
        migrations.AlterField(
            model_name='category',
            name='thumbnail_image_alt_text_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt text'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='categories_title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Header of Featured Articles'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='categories_title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Header of Featured Articles'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='category_title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Categories Header'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='category_title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Categories Header'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='meta_description_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='meta_description_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='meta_keywords_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='meta_keywords_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='post',
            name='banner_image',
            field=models.ImageField(upload_to='banner_posts', verbose_name='banner image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt_en',
            field=models.TextField(null=True, verbose_name='excerpt'),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt_fr',
            field=models.TextField(null=True, verbose_name='excerpt'),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_description_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_description_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_keywords_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_keywords_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(upload_to='posts', verbose_name='Content Image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image_alt_text_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image_alt_text_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt text'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug_en',
            field=models.SlugField(max_length=255, null=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug_fr',
            field=models.SlugField(max_length=255, null=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitle_en',
            field=models.CharField(max_length=255, null=True, verbose_name='sub title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitle_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='sub title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
    ]
