# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-04 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GastronomyLanding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('title_fr', models.CharField(max_length=255, verbose_name='Title')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title')),
                ('excerpt', models.TextField(verbose_name='Excerpt')),
                ('excerpt_fr', models.TextField(verbose_name='Excerpt')),
                ('excerpt_en', models.TextField(verbose_name='Excerpt')),
                ('banner_image', models.ImageField(upload_to=b'gastronomy_landing_banner', verbose_name='Banner image')),
                ('heading', models.TextField(verbose_name='Location description')),
                ('heading_en', models.TextField(verbose_name='Location description')),
                ('heading_fr', models.TextField(verbose_name='Location description')),
                ('description', models.TextField(verbose_name='Sub Heading')),
                ('description_en', models.TextField(verbose_name='Sub Heading')),
                ('description_fr', models.TextField(verbose_name='Sub Heading')),
                ('image', models.ImageField(upload_to=b'gastronomy_location', verbose_name='Location image')),
            ],
            options={
                'verbose_name': 'Gastronomy Landing',
            },
        ),
        migrations.CreateModel(
            name='GastronomySection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('title_fr', models.CharField(max_length=255, verbose_name='Title')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title')),
                ('sub_title', models.TextField(verbose_name='Sub Title')),
                ('sub_title_fr', models.TextField(verbose_name='Sub Title')),
                ('sub_title_en', models.TextField(verbose_name='Sub Title')),
                ('excerpt', models.TextField(verbose_name='Excerpt')),
                ('excerpt_fr', models.TextField(verbose_name='Excerpt')),
                ('excerpt_en', models.TextField(verbose_name='Excerpt')),
                ('banner_image', models.ImageField(upload_to=b'gastronomy_section_banner', verbose_name='Banner image')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastronomy_sections', to='Gastronomy.GastronomyLanding')),
            ],
            options={
                'verbose_name': 'Gastronomy Section',
                'verbose_name_plural': 'Gastronomy Sections',
            },
        ),
    ]
