# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-16 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gastronomy', '0002_initial_config'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gastronomysection',
            options={'ordering': ('order',), 'verbose_name': 'Gastronomy Section', 'verbose_name_plural': 'Gastronomy Sections'},
        ),
        migrations.RemoveField(
            model_name='gastronomysection',
            name='configuration',
        ),
        migrations.AddField(
            model_name='gastronomysection',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='order'),
        ),
    ]
