# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-01 12:56
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gastronomy', '0004_auto_20161116_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastronomysection',
            name='excerpt',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Excerpt'),
        ),
        migrations.AlterField(
            model_name='gastronomysection',
            name='excerpt_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Excerpt'),
        ),
        migrations.AlterField(
            model_name='gastronomysection',
            name='excerpt_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Excerpt'),
        ),
        migrations.AlterField(
            model_name='gastronomysection',
            name='sub_title',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Sub Title'),
        ),
        migrations.AlterField(
            model_name='gastronomysection',
            name='sub_title_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Sub Title'),
        ),
        migrations.AlterField(
            model_name='gastronomysection',
            name='sub_title_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Sub Title'),
        ),
    ]
