# Generated by Django 2.2.4 on 2019-09-11 13:45

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gastronomy', '0010_auto_20171024_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastronomylanding',
            name='description_es',
            field=models.TextField(null=True, verbose_name='Sub Heading'),
        ),
        migrations.AddField(
            model_name='gastronomylanding',
            name='excerpt_es',
            field=models.TextField(null=True, verbose_name='sub title'),
        ),
        migrations.AddField(
            model_name='gastronomylanding',
            name='heading_es',
            field=models.TextField(null=True, verbose_name='Location description'),
        ),
        migrations.AddField(
            model_name='gastronomylanding',
            name='image_alt_text_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt text'),
        ),
        migrations.AddField(
            model_name='gastronomylanding',
            name='meta_description_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='gastronomylanding',
            name='meta_keywords_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='gastronomylanding',
            name='title_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='gastronomysection',
            name='button_text_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='button text'),
        ),
        migrations.AddField(
            model_name='gastronomysection',
            name='excerpt_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Excerpt'),
        ),
        migrations.AddField(
            model_name='gastronomysection',
            name='sub_title_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Sub Title'),
        ),
        migrations.AddField(
            model_name='gastronomysection',
            name='title_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='gastronomylanding',
            name='banner_image',
            field=models.ImageField(upload_to='gastronomy_landing_banner', verbose_name='Banner image'),
        ),
        migrations.AlterField(
            model_name='gastronomylanding',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Sub Heading'),
        ),
        migrations.AlterField(
            model_name='gastronomylanding',
            name='description_fr',
            field=models.TextField(null=True, verbose_name='Sub Heading'),
        ),
        migrations.AlterField(
            model_name='gastronomylanding',
            name='excerpt_en',
            field=models.TextField(null=True, verbose_name='sub title'),
        ),
        migrations.AlterField(
            model_name='gastronomylanding',
            name='excerpt_fr',
            field=models.TextField(null=True, verbose_name='sub title'),
        ),
        migrations.AlterField(
            model_name='gastronomylanding',
            name='heading_en',
            field=models.TextField(null=True, verbose_name='Location description'),
        ),
        migrations.AlterField(
            model_name='gastronomylanding',
            name='heading_fr',
            field=models.TextField(null=True, verbose_name='Location description'),
        ),
        migrations.AlterField(
            model_name='gastronomylanding',
            name='image',
            field=models.ImageField(upload_to='gastronomy_location', verbose_name='Location image'),
        ),
        migrations.AlterField(
            model_name='gastronomylanding',
            name='image_alt_text_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt text'),
        ),
        migrations.AlterField(
            model_name='gastronomylanding',
            name='image_alt_text_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt text'),
        ),
        migrations.AlterField(
            model_name='gastronomylanding',
            name='meta_description_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='gastronomylanding',
            name='meta_description_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='gastronomylanding',
            name='meta_keywords_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='gastronomylanding',
            name='meta_keywords_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='gastronomylanding',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='gastronomylanding',
            name='title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='gastronomysection',
            name='banner_image',
            field=models.ImageField(upload_to='gastronomy_section_banner', verbose_name='Banner image'),
        ),
        migrations.AlterField(
            model_name='gastronomysection',
            name='button_text_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='button text'),
        ),
        migrations.AlterField(
            model_name='gastronomysection',
            name='button_text_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='button text'),
        ),
        migrations.AlterField(
            model_name='gastronomysection',
            name='excerpt_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Excerpt'),
        ),
        migrations.AlterField(
            model_name='gastronomysection',
            name='excerpt_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Excerpt'),
        ),
        migrations.AlterField(
            model_name='gastronomysection',
            name='sub_title_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Sub Title'),
        ),
        migrations.AlterField(
            model_name='gastronomysection',
            name='sub_title_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Sub Title'),
        ),
        migrations.AlterField(
            model_name='gastronomysection',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='gastronomysection',
            name='title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
    ]
