# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-22 09:58
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0002_initial_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='longitude',
        ),
        migrations.AddField(
            model_name='contact',
            name='position',
            field=geoposition.fields.GeopositionField(blank=True, max_length=42, null=True, verbose_name='position'),
        ),
    ]
