# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-05 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0004_auto_20161123_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspiration',
            name='blank',
            field=models.BooleanField(default=False, help_text='Open link in another tab', verbose_name='Target Blank'),
        ),
        migrations.AddField(
            model_name='slide',
            name='blank',
            field=models.BooleanField(default=False, help_text='Open link in another tab', verbose_name='Target Blank'),
        ),
    ]
