# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-27 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0005_auto_20161205_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='order')),
            ],
            options={
                'ordering': ['order'],
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ContactGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='phone')),
                ('toll_free', models.CharField(blank=True, max_length=20, verbose_name='toll free')),
                ('web_site', models.URLField(blank=True, verbose_name='web site')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='CMS.Category', verbose_name='category')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Contact Group',
                'verbose_name_plural': 'Contacts Group',
            },
        ),
    ]
