# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-28 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0008_auto_20170214_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='contact',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255, verbose_name='Keywords'),
        ),
    ]
