# Generated by Django 2.2.4 on 2019-09-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0011_auto_20171024_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_es',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='contact',
            name='description_es',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='contact',
            name='excerpt_es',
            field=models.TextField(null=True, verbose_name='sub title'),
        ),
        migrations.AddField(
            model_name='contact',
            name='meta_description_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='contact',
            name='meta_keywords_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='contact',
            name='title_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='contactgroup',
            name='name_es',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='inspiration',
            name='image_alt_text_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt text'),
        ),
        migrations.AddField(
            model_name='inspiration',
            name='title_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='slide',
            name='title_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='banner_image',
            field=models.ImageField(upload_to='contact', verbose_name='Banner Image'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='description_fr',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='excerpt_en',
            field=models.TextField(null=True, verbose_name='sub title'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='excerpt_fr',
            field=models.TextField(null=True, verbose_name='sub title'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='meta_description_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='meta_description_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='meta_keywords_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='meta_keywords_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='contactgroup',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='contactgroup',
            name='name_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='inspiration',
            name='image',
            field=models.ImageField(upload_to='inspiration', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='inspiration',
            name='image_alt_text_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt text'),
        ),
        migrations.AlterField(
            model_name='inspiration',
            name='image_alt_text_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt text'),
        ),
        migrations.AlterField(
            model_name='inspiration',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='inspiration',
            name='title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='banner_image',
            field=models.ImageField(upload_to='banners', verbose_name='Banner Image'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='button_image_color',
            field=models.ImageField(blank=True, upload_to='banners', verbose_name='Button icon color'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='button_image_white',
            field=models.ImageField(blank=True, upload_to='banners', verbose_name='Button icon white'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
    ]
