# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-30 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('title_en', models.CharField(max_length=255, verbose_name='title')),
                ('title_fr', models.CharField(max_length=255, verbose_name='title')),
                ('subtitle', models.CharField(max_length=255, verbose_name='sub title')),
                ('subtitle_en', models.CharField(max_length=255, verbose_name='sub title')),
                ('subtitle_fr', models.CharField(max_length=255, verbose_name='sub title')),
                ('excerpt', models.TextField(verbose_name='excerpt')),
                ('excerpt_fr', models.TextField(verbose_name='excerpt')),
                ('excerpt_en', models.TextField(verbose_name='excerpt')),
                ('description', models.TextField(verbose_name='description')),
                ('description_fr', models.TextField(verbose_name='description')),
                ('description_en', models.TextField(verbose_name='description')),
                ('banner_image', models.ImageField(upload_to=b'asomarte_banner', verbose_name='banner image')),
                ('web_site', models.URLField(blank=True, max_length=255, verbose_name='web site')),
                ('magazine_image', models.ImageField(blank=True, upload_to=b'asomarte_magazines', verbose_name='magazine image')),
                ('magazine_url', models.URLField(blank=True, max_length=255, verbose_name='magazine url')),
                ('magazine_pdf', models.FileField(blank=True, upload_to=b'asomarte_pdfs', verbose_name='magazine pdf')),
            ],
            options={
                'verbose_name': 'Configuration',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('title_en', models.CharField(max_length=255, verbose_name='title')),
                ('title_fr', models.CharField(max_length=255, verbose_name='title')),
                ('link', models.URLField(max_length=255, verbose_name='Link')),
                ('excerpt', models.TextField(verbose_name='Excerpt')),
                ('excerpt_fr', models.TextField(verbose_name='Excerpt')),
                ('excerpt_en', models.TextField(verbose_name='Excerpt')),
                ('image', models.ImageField(max_length=255, upload_to=b'videos', verbose_name='Image')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
    ]
