# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-14 15:33
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asomarte', '0003_video_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='description_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='description'),
        ),
    ]
