# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-19 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asomarte', '0004_auto_20161214_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='magazine_pdf',
        ),
    ]
