# Generated by Django 2.2.4 on 2019-09-11 13:45

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asomarte', '0008_auto_20171024_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='description_es',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='excerpt_es',
            field=models.TextField(null=True, verbose_name='excerpt'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='magazine_image_alt_text_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt text'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='meta_description_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='meta_keywords_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='subtitle_es',
            field=models.CharField(max_length=255, null=True, verbose_name='sub title'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='title_es',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='video',
            name='excerpt_es',
            field=models.TextField(null=True, verbose_name='Excerpt'),
        ),
        migrations.AddField(
            model_name='video',
            name='image_alt_text_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt text'),
        ),
        migrations.AddField(
            model_name='video',
            name='title_es',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='banner_image',
            field=models.ImageField(upload_to='asomarte_banner', verbose_name='banner image'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='description_fr',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='excerpt_en',
            field=models.TextField(null=True, verbose_name='excerpt'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='excerpt_fr',
            field=models.TextField(null=True, verbose_name='excerpt'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='magazine_image',
            field=models.ImageField(blank=True, upload_to='asomarte_magazines', verbose_name='magazine image'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='magazine_image_alt_text_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt text'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='magazine_image_alt_text_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt text'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='meta_description_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='meta_description_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='meta_keywords_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='meta_keywords_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='subtitle_en',
            field=models.CharField(max_length=255, null=True, verbose_name='sub title'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='subtitle_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='sub title'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='video',
            name='excerpt_en',
            field=models.TextField(null=True, verbose_name='Excerpt'),
        ),
        migrations.AlterField(
            model_name='video',
            name='excerpt_fr',
            field=models.TextField(null=True, verbose_name='Excerpt'),
        ),
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.ImageField(max_length=255, upload_to='videos', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='video',
            name='image_alt_text_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt text'),
        ),
        migrations.AlterField(
            model_name='video',
            name='image_alt_text_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt text'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
    ]
